[package]
name = "capto-audio"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Audio device enumeration for Capto"

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
cpal = "0.15"

[target."cfg(windows)".dependencies]
wasapi = "0.23.0"
